# MULTIPLE LINEAR REGRESSION

- more than two variables 
- one dependent and more than one independent variables
- independent variables are also called as input data or features
- dependent variables are also called as prdiction or output

In [1]:
#import libararies
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [1]:
# import dataset
df= pd.read_csv("multivarSalary.csv")

NameError: name 'pd' is not defined

In [3]:
df.columns

Index(['age', 'distance', 'YearsExperience', 'Salary'], dtype='object')

In [4]:
df1= df
df1.head()

age  distance  YearsExperience  Salary
0  31.1     77.75              1.1   39343
1  31.3     78.25              1.3   46205
2  31.5     78.75              1.5   37731
3  32.0     80.00              2.0   43525
4  32.2     80.50              2.2   39891

In [5]:
##assigning x and y from the dataset
X = df1.iloc[:, :-1].values #get a copy of dataset exclude last column
y = df1.iloc[:, 3].values #get array of dataset in column 1st

In [6]:
X.shape

(30, 3)

In [7]:
y

array([ 39343,  46205,  37731,  43525,  39891,  56642,  60150,  54445,
        64445,  57189,  63218,  55794,  56957,  57081,  61111,  67938,
        66029,  83088,  81363,  93940,  91738,  98273, 101302, 113812,
       109431, 105582, 116969, 112635, 122391, 121872], dtype=int64)

In [8]:
# creat and fit your model
model= LinearRegression().fit(X,y)
model

LinearRegression()

In [9]:
model.coef_

array([-2.68055892e+15,  1.06092560e+15,  2.82449143e+13])

In [10]:
model.intercept_

847347429532075.5

In [11]:
# 'open', 'close', 'low', 'high'
response= model.predict([['32.2','80.50','2.2']])
response

C:\Users\Azka\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)


array([46614.75])

In [ ]:
#efficacy of model

In [ ]:
#efficacy of model
reg= LinearRegression().fit(X, y)
print("score test = ",reg.score(X, y) )
print("score train = ",reg.score(X, y))

score test =  0.9569520722791693
score train =  0.9569520722791693


In [ ]:
model.score(X, y)